<%--
  Created by IntelliJ IDEA.
  User: esosa
  Date: 2024-03-30
  Time: 2:48 p.m.
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ page import="com.HotelBooking.Customer" %>
<%@ page import="com.HotelBooking.CustomerService" %>
<%@ page import="java.util.List" %>
<%@ page import="java.io.IOException" %>
<%@ page import="java.sql.SQLException" %>
<%@ page import="java.io.PrintWriter" %>
<%@ page import="java.sql.Date" %>

<%
    CustomerService customerService = new CustomerService();
    List<Customer> customers = null;
    String message = null;

    // Get all customers
    try {
        customers = customerService.getCustomers();
    } catch (SQLException | IOException e) {
        message = "An error occurred while fetching customers: " + e.getMessage();
    } catch (Exception e) {
        message = "An unexpected error occurred: " + e.getMessage();
    }

    // Handle form submission to create a new customer
    if ("POST".equalsIgnoreCase(request.getMethod())) {
        String name = request.getParameter("name");
        String registrationDateStr = request.getParameter("registrationDate");
        int streetNumber = Integer.parseInt(request.getParameter("streetNumber"));
        String streetName = request.getParameter("streetName");
        String postalCode = request.getParameter("postalCode");
        // Parse other form parameters as needed

        try {
            // Perform validation and create the customer
            // For simplicity, assuming all parameters are valid and required
            Customer newCustomer = new Customer(
                    0, // ID will be auto-generated by the database
                    name,
                    Date.valueOf(registrationDateStr),
                    streetNumber,
                    streetName,
                    postalCode
                    // Parse other form parameters as needed
            );
            String createMessage = customerService.createCustomer(newCustomer);
            if (!createMessage.startsWith("Customer successfully inserted!")) {
                message = "Error creating customer: " + createMessage;
            }
        } catch (Exception e) {
            message = "An error occurred while creating customer: " + e.getMessage();
        }
    }
%>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customers Management</title>
</head>
<body>
<h1>Customers Management</h1>

<% if (message != null) { %>
<p><%= message %></p>
<% } %>

<table border="1">
    <thead>
    <tr>
        <th>Customer ID</th>
        <th>Name</th>
        <th>Registration Date</th>
        <th>Street Number</th>
        <th>Street Name</th>
        <th>Postal Code</th>
        <!-- Add more columns as needed -->
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <% if (customers != null) {
        for (Customer customer : customers) { %>
    <tr>
        <td><%= customer.getCustomerID() %></td>
        <td><%= customer.getName() %></td>
        <td><%= customer.getRegistrationDate() %></td>
        <td><%= customer.getStreetNumber() %></td>
        <td><%= customer.getStreetName() %></td>
        <td><%= customer.getPostalCode() %></td>
        <!-- Add more columns as needed -->
        <td>
            <!-- Link to delete customer -->
            <form action="deleteCustomer.jsp" method="post">
                <input type="hidden" name="customerID" value="<%= customer.getCustomerID() %>">
                <input type="submit" value="Delete">
            </form>
        </td>
    </tr>
    <%  }
    } %>
    </tbody>
</table>

<hr>

<h2>Add Customer</h2>
<form action="" method="post">
    <!-- Input fields for creating a new customer -->
    <label for="name">Name:</label>
    <input type="text" id="name" name="name" required><br>

    <label for="registrationDate">Registration Date:</label>
    <input type="date" id="registrationDate" name="registrationDate" required><br>

    <label for="streetNumber">Street Number:</label>
    <input type="text" id="streetNumber" name="streetNumber" required><br>

    <label for="streetName">Street Name:</label>
    <input type="text" id="streetName" name="streetName" required><br>

    <label for="postalCode">Postal Code:</label>
    <input type="text" id="postalCode" name="postalCode" required><br>

    <input type="submit" value="Add Customer">
</form>
</body>
</html>
